DISPLAY_ROOT := $(abs_srctree)/techpack/display

KERNEL_ROOT := $(abs_srctree)
KERNEL_SRC  := $(abs_srctree)
MACHINE := qcm6490
SOC_FAM := qcm6490

export DISPLAY_ROOT
export KERNEL_ROOT
export MACHINE
export SOC_FAM
export HEADERS_DIR

obj-y += display/
